services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8080:80"  # Map to standard Apache port
      - "5173:5173" # For Vite
    volumes:
      - .:/var/www/html:z
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel_app
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
  db:
    image: docker.io/library/mariadb:11.8
    hostname: db
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: laravel_app
      MARIADB_USER: laravel_user
      MARIADB_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
